### ISSUE TITLE
vuetelescope.com is really slow

### ISSUE THREAD

**Issue by vanling** [nuxtlabs/vue-telescope-analyzer#100]
Unable to open https://www.vuetelescope.com/explore. 
This also slows down https://nuxt.com/showcase i guess

**Comment by kaikaibenkai** [comment]
VueTelescope will traverse the entire DOM tree multiple times. That's why it's slow, I think.

**Comment by vanling** [comment]
I think it was more of an server/infra issue. It's a lot faster at this moment. Closing ticket.
