### ISSUE TITLE
How to force a rescan of a site already archived in vuetelescope.com ?

### ISSUE THREAD

**Issue by stefanobartoletti** [nuxtlabs/vue-telescope-analyzer#43]
As the title says, is it possible to force a rescan of a site which was already saved on Telescope website? And how to do so?

It could be useful if some technologies were changed (maybe some plugin, or a UI ramework, and so on).

**Comment by stefanobartoletti** [comment]
It is https://bricks.stefanobartoletti.it/ . It's a documentation site, I'm currently working on it. I started by testing Docus (you may have heard of it ;) ), but maybe it is too early for a production site adoption, and decided to switch to VuePress for now.

Anyway, there is no hurry, if the cache resets after a month I'm fine :)

**Comment by Atinux** [comment]
It's updated! The screenshot is cached and will take some time to reflect.

We are working hard to release Docus in the upcoming weeks, it gives so much power compared to other alternatives (and based on Nuxt + Vite 🔥 )

**Comment by stefanobartoletti** [comment]
Thank you for your work on Docus, it is indeed an interesting project, but I took the opportunity to study even another framework (I love everything that is related to Vue). Usually Nuxt is my weapon of choice anyway ;)

Anyway at the moment VuePress gave me a most needed feature: being able to have a dark header while the rest of the site is light :D
