### ISSUE TITLE
It seems vue telescope analyzer did not recognize windicss instead it recognized it as tailwind.

### ISSUE THREAD

**Issue by BroJenuel** [nuxtlabs/vue-telescope-analyzer#61]
This is WindiCSS website, and it was built using windiCSS. But the Vue telescope recognized it as tailwindcss.

![image](https://user-images.githubusercontent.com/31676163/138049625-10bb2746-ac06-4fd4-841f-9b661f51278f.png)

**Comment by Atinux** [comment]
See discussion in https://github.com/nuxtlabs/vue-telescope-analyzer/issues/55
