### ISSUE TITLE
Support folder path

### ISSUE THREAD

**Issue by PhantasWeng** [nuxtlabs/vue-telescope-analyzer#66]
### Is your feature request related to a problem? Please describe.

For some organization, will have several sites located on folder path as its root.
So far Vue telescope only support top domain.

### Describe the solution you'd like

add support for folder path root site.

### Additional context

For example:
https://www.owlting.com
https://www.owlting.com/owljourney
https://www.owlting.com/experiences
https://www.owlting.com/market

**Comment by Atinux** [comment]
Thanks @PhantasWeng 

Actually only vuetelescope.com does not support sub path, if you use the extension it should work :)
