### ISSUE TITLE
Can you open source the official website of `vue telescope`?

### ISSUE THREAD

**Issue by kw214** [nuxtlabs/vue-telescope-analyzer#69]
Can you open source the official website of `vue telescope`?

**Comment by Atinux** [comment]
We are reworking it with Nuxt 3 & Content V2 and I believe we can make it open source.

The API is based on Strapi and don't know if we could open source it though

**Comment by Atinux** [comment]
It is now open source: https://github.com/nuxtlabs/vue-telescope-website
