### ISSUE TITLE
bug: `@nuxt/image` recognised even when it's not actually used

### ISSUE THREAD

**Issue by Lexpeartha** [nuxtlabs/vue-telescope-analyzer#83]
### Version

vue-telescope-analyzer: `v0.9.14`

### Reproduction Link
Deployed build: https://nuxt-xstate.netlify.app/
Source code (playground of the module): https://github.com/Lexpeartha/nuxt-xstate

### Steps to reproduce

Just deploying the given code

### What is Expected?
Extension shows only used modules/libraries

### What is actually happening?
Extension actually shows that site uses image module, even tho It doesn't even have a plain old image

Tested on some other small projects like this, similar case. `@nuxt/image` is "recognised" even if it isn't there

**Comment by Lexpeartha** [comment]
Seems like this returns truthy value on such websites: 
```
[...document.querySelectorAll('*')].map((el) => el.__vue_app__?.config?.globalProperties?.$router).filter(Boolean).length
```

**Comment by Atinux** [comment]
Fixed, thank you for your fast feedback!
