### ISSUE TITLE
Harlem support

### ISSUE THREAD

**Issue by Lexpeartha** [nuxtlabs/vue-telescope-analyzer#86]
Support for recognizing [Harlem](https://harlemjs.com/) as a vue plugin. It could be done in a similar way it is currently done with pinia, and I would be more than happy to make PR if I get a green light 👍🏽

**Comment by danielroe** [comment]
That seems good to me; wdyt @atinux?

**Comment by Atinux** [comment]
Sure, PR welcome @Lexpeartha !

**Comment by Lexpeartha** [comment]
I've tried to detect it in the same way it is done with pinia, however seems harlem is different.
Created andrewcourtice/harlem#67 to get some input from the library creator about this, since I wasn't able to find anything actually traceable
