### ISSUE TITLE
Website + Plugin is broken "

### ISSUE THREAD

**Issue by madebyfabian** [nuxtlabs/vue-telescope-analyzer#91]
### Version

vue-telescope-analyzer: 1.6.1

### Steps to reproduce

Just go on the website, enter an url. It errors:

<img width="160" alt="Klein (Bildschirm­foto 2023-02-11 um 06 28 24)" src="https://user-images.githubusercontent.com/32813692/218242117-8ddf0eaf-3683-42b4-8362-12482a5a6a34.png">

Network Tab:
```json
{
    "error": true,
    "message": "FetchError: request to https://awis.api.alexa.com/api?Action=urlInfo&Output=json&ResponseGroup=Rank&Url=madebyfabian.com failed, reason: getaddrinfo ENOTFOUND awis.api.alexa.com"
}
```

The extension "Save" button also does not work, suppose it's the same.

### What is Expected?

No error :)

### What is actually happening?

Error :)

**Comment by Atinux** [comment]
Damn it's true that they removed Alexa API

**Comment by Atinux** [comment]
It's now fixed! https://www.vuetelescope.com/explore/madebyfabian-com
