### ISSUE TITLE
Extension doesn't work on the localhost

### ISSUE THREAD

**Issue by Pyr33x** [nuxtlabs/vue-telescope-analyzer#92]
### Version
1.6.1

### Steps to reproduce
1. Run your website on a localhost
2. Try using extension

### What is Expected?
Just extension gotta work

### What is actually happening?
When you run your website on a localhost and when you click on the extension it says: Please enter an url in the address bar.

### Screenshot
![image](https://user-images.githubusercontent.com/83529331/219848011-7355c075-3404-48d9-9e5f-c02870f46cc4.png)

**Comment by Atinux** [comment]
Happy to help on https://github.com/nuxtlabs/vue-telescope-extensions ?
