### ISSUE TITLE
Unable to submit site to vue telescope

### ISSUE THREAD

**Issue by TechAkayy** [nuxtlabs/vue-telescope-analyzer#94]
When I try submitting a Iles app deployed on netlify, I'm getting invalid URL. 

https://natures-delight-with-iles-tailwindcss.netlify.app/

![image](https://user-images.githubusercontent.com/73772701/235936965-50b2a502-ea09-453b-945f-c3a79da21976.png)

**Comment by Atinux** [comment]
We actually disallows indexing *.netlify.app domains directly
